# Generated by Django 3.0 on 2020-06-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoad_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_input',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
