# Generated by Django 3.0 on 2020-06-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoad_app', '0002_auto_20200604_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.BigIntegerField()),
                ('product', models.CharField(max_length=200)),
                ('proposal_no', models.BigIntegerField()),
                ('inwardnumber', models.CharField(max_length=250)),
                ('currentworkstep', models.CharField(max_length=200)),
                ('names', models.CharField(max_length=100)),
                ('customer_names', models.CharField(max_length=200)),
            ],
        ),
    ]
